---
- name: Install common packages
  block:
    - name: Include OS-specific variables
      ansible.builtin.include_vars: "{{ var_file }}"
      with_first_found:
        - "{{ role_path }}/vars/{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
        - "{{ role_path }}/vars/{{ ansible_os_family }}-{{ ansible_distribution_major_version }}.yml"
        - "{{ role_path }}/vars/{{ ansible_distribution }}.yml"
        - "{{ role_path }}/vars/{{ ansible_os_family }}.yml"
        - "{{ role_path }}/vars/{{ ansible_lsb.id }}.yml"
      loop_control:
        loop_var: var_file

    - name: Include OS-specific common packages installation
      ansible.builtin.include_tasks: "{{ task_file }}"
      with_first_found:
        - "{{ role_path }}/tasks/noauto_install_common_{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
        - "{{ role_path }}/tasks/noauto_install_common_{{ ansible_os_family }}-{{ ansible_distribution_major_version }}.yml"
        - "{{ role_path }}/tasks/noauto_install_common_{{ ansible_distribution }}.yml"
        - "{{ role_path }}/tasks/noauto_install_common_{{ ansible_os_family }}.yml"
        - "{{ role_path }}/tasks/noauto_install_common_{{ ansible_lsb.id }}.yml"
      loop_control:
        loop_var: task_file
