---
- name: Ensure we are using apk
  ansible.builtin.fail:
    msg: "This role only supports {{ ansible_os_family }} systems that use apk as a package manager."
  when: ansible_pkg_mgr != "apk"

- name: Install common packages via apk
  block:
    - name: Update apk cache
      community.general.apk:
        update_cache: true
      changed_when: false # The apk module currently does not support cache_valid_time.
      become: true

    - name: Install package dependencies first (if specified)
      community.general.apk:
        name: "{{ dependency }}"
        state: present
      loop: "{{ common_pkgs_apk.install | selectattr('depends', 'defined') | map(attribute='depends') | flatten }}"
      loop_control:
        loop_var: dependency
      become: true

    - name: Ensure common apk packages are installed
      community.general.apk:
        name: "{{ package.name if package is mapping else package }}"
        state: present
      loop: "{{ common_pkgs_apk.install }}"
      loop_control:
        loop_var: package
      become: true
